import type { ScheduledTaskDto } from "types";

export const testSchedule: ScheduledTaskDto[] = [
  {
    eid: "ue31_rec0",
    priority: 4,
    duration: 3600,
    separable: false,
    prefer_startunix: 1704139200,
    recurring: "daily",
    recurring_parent: "ue31",
    participants: [
      {
        uid: "u5",
        name: `name-of-u5`,
        alias: `alias-of-u5`,
        profilePicture: "https://picsum.photos/200",
        languages: ["English"],
      },
    ],
    residents: [
      {
        uid: "p1",
        name: `name-of-p1`,
        alias: `alias-of-p1`,
        profilePicture: "https://picsum.photos/200",
        languages: ["English"],
        allergies: ["Nuts", "Ampicillin"],
        room: "Room 1-3-4",
      },
    ],
    add_unix: 1704648600,
    status: 2,
    recurrance: 0,
    score: 4.344586657028665,
    time: 1704155400,
    limit_start_timeslot: 28800,
    limit_end_timeslot: 39600,
    facility: "NTUC Health Nursing Home\n(Geylang East)",
    task_name: "Bathing",
    logistics: "Towel, Non-slip slippers",
  },
  {
    eid: "ue31_rec1",
    priority: 5,
    duration: 3600,
    separable: false,
    prefer_startunix: 1704225600,
    recurring: "daily",
    recurring_parent: "ue31",
    participants: [
      {
        uid: "u5",
        name: `name-of-u5`,
        alias: `alias-of-u5`,
        profilePicture: "https://picsum.photos/200",
        languages: ["English"],
      },
    ],
    residents: [
      {
        uid: "p1",
        name: `name-of-p1`,
        alias: `alias-of-p1`,
        profilePicture: "https://picsum.photos/200",
        languages: ["English"],
        allergies: ["Nuts", "Ampicillin"],
        room: "Room 1-3-4",
      },
      {
        uid: "p2",
        name: `name-of-p2`,
        alias: `alias-of-p2`,
        profilePicture: "https://picsum.photos/200",
        languages: ["English"],
        allergies: ["Milk", "Doxycyline"],
        room: "Room 1-3-5",
      },
    ],
    add_unix: 1704648600,
    status: 2,
    recurrance: 1,
    score: 5.344586657028665,
    time: 1704324600,
    limit_start_timeslot: 25200,
    limit_end_timeslot: 28800,
    facility: "NTUC Health Nursing Home\n(Geylang East)",
    task_name: "Croquet duel",
    logistics: "Mallets, Balls",
  },
];
